import NavBar from '@/components/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
import styles from '../styles/AllStyles.module.css'
import MySessionProvider from './SessionProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CRUD APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MySessionProvider>
   
      <body className={inter.className}>
        <div className={styles.navbar_div}>
        <NavBar/>

        </div>
       
        {children}
        </body>
      
        </MySessionProvider>
    </html>
  )
}
